### ISSUE TITLE
Missing properties in `climex` notebook causes conversion failure

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/pavics-sdi#305]
@huard 
I have seen this error a few times in birdhouse-deploy CI tests.
I guess that probably only requires rerunning the notebook with a more recent Jupyter version to apply the metadata, or maybe this is something the Nb pre-commit incorrectly strips out?

```bash
10:47:23  + jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=240 --allow-errors --output-dir buildout --output climex.output.ipynb pavics-sdi-master/docs/source/notebooks/climex.ipynb
10:47:25  [NbConvertApp] Converting notebook pavics-sdi-master/docs/source/notebooks/climex.ipynb to notebook
10:47:25  [NbConvertApp] ERROR | Notebook JSON is invalid: 'name' is a required property
10:47:25  
10:47:25  Failed validating 'required' in notebook['properties']['metadata']['properties']['kernelspec']:
10:47:25  
10:47:25  On instance['metadata']['kernelspec']:
10:47:25  {'language': 'python'}
10:47:25  [NbConvertApp] ERROR | Notebook is invalid after preprocessor <nbconvert.preprocessors.tagremove.TagRemovePreprocessor object at 0x7f8e4c937760>
10:47:25  Traceback (most recent call last):
10:47:25    File "/opt/conda/envs/birdy/bin/jupyter-nbconvert", line 10, in <module>
10:47:25      sys.exit(main())
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/jupyter_core/application.py", line 277, in launch_instance
10:47:25      return super().launch_instance(argv=argv, **kwargs)
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/traitlets/config/application.py", line 1043, in launch_instance
10:47:25      app.start()
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 414, in start
10:47:25      self.convert_notebooks()
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 589, in convert_notebooks
10:47:25      self.convert_single_notebook(notebook_filename)
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 555, in convert_single_notebook
10:47:25      output, resources = self.export_single_notebook(
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 481, in export_single_notebook
10:47:25      output, resources = self.exporter.from_filename(
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 201, in from_filename
10:47:25      return self.from_file(f, resources=resources, **kw)
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 220, in from_file
10:47:25      return self.from_notebook_node(
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/nbconvert/exporters/notebook.py", line 36, in from_notebook_node
10:47:25      nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 154, in from_notebook_node
10:47:25      nb_copy, resources = self._preprocess(nb_copy, resources)
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 354, in _preprocess
10:47:25      self._validate_preprocessor(nbc, preprocessor)
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 321, in _validate_preprocessor
10:47:25      nbformat.validate(nbc, relax_add_props=True)
10:47:25    File "/opt/conda/envs/birdy/lib/python3.9/site-packages/nbformat/validator.py", line 502, in validate
10:47:25      raise error
10:47:25  nbformat.validator.NotebookValidationError: 'name' is a required property
```

**Comment by fmigneault** [comment]
More recently, the timeout of the convertion is reached intead of the validation error 
```pytb
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 240 seconds.
```

Similar to https://github.com/Ouranosinc/PAVICS-landing/issues/72

**Comment by fmigneault** [comment]
reference: https://gitlab.com/crim.ca/clients/daccs/daccs-e2e-jenkins/-/merge_requests/24

**Comment by fmigneault** [comment]
`SAVE_RESULTING_NOTEBOOK=false` is now enabled by default (still overridable manually)
CI execution time ~40-48min => ~21min. 
No more `CellTimeoutError`. 

Latest run doesn't show any output error in `climex.ipynb`.
